name = "cake"
version = "2.0.0"
description = "An SQL query builder for Gleam for SQL dialects ğŸ˜PostgreSQL, ğŸª¶SQLite, ğŸ¦­MariaDB, and ğŸ¬MySQL"
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-cake" }
# links = [{ title = "Website", href = "https://gleam.run" }]

gleam = ">= 1.4.0 and < 2.0.0"

[documentation]
pages = [
  { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.1.8 and < 2.0.0"
gleam_pgo = ">= 0.13.0 and < 2.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"
gmysql = ">= 1.4.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
sqlight = ">= 0.9.0 and < 2.0.0"
