name = "cake_demo_select_and_decode"
description = "An demo of using Gleam with Cake and ğŸ˜PostgreSQL to run SELECT queries and decode returning data into Gleam records"

[dependencies]
cake = { path = "../../../../" }
helper = { path = "../../helper" }
gleam_pgo = ">= 0.13.0 and < 2.0.0"
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
