name = "cake_demo_select_and_decode"
description = "A demo of using Gleam with Cake and ğŸ˜PostgreSQL to run SELECT queries and decode returning data into Gleam records"
gleam = ">= 1.11.1"

[dependencies]
# cake = ">= 2.1.2 and < 3.0.0"
cake = { path = "../../" }
cake_pog = ">= 1.2.0 and < 2.0.0"
gleam_stdlib = ">= 0.61.0 and < 2.0.0"
examples_helper = { path = "../examples_helper" }
