name = "cake_demo_insert"
description = "An demo of using Gleam with Cake and ğŸ˜PostgreSQL to run INSERT queries"

[dependencies]
cake = { path = "../../../../" }
helper = { path = "../../helper" }
pog = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
