name = "cake_demo_prepared_fragment"
description = "An demo of using Gleam with Cake and ğŸ˜PostgreSQL to run queries with fragments including prepared statements"

[dependencies]
cake = { path = "../../../.." }
cake_pog = ">= 1.0.3 and < 2.0.0"
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
helper = { path = "../../helper" }
pog = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
