name = "cake_demo_update"
description = "An demo of using Gleam with Cake and ğŸ˜PostgreSQL to run UPDATE queries"
version = "1.1.0"
gleam = ">= 1.10.0"

[dependencies]
cake = { path = "../../../.." }
cake_pog = ">= 4.0.0 and < 5.0.0"
gleam_stdlib = ">= 0.61.0 and < 2.0.0"
helper = { path = "../../helper" }
pog = ">= 4.0.0 and < 3.0.0"
